### PR TITLE
Exit with non-zero exit code on exception

### LINKED ISSUE #898: Unhandled python exceptions do not result in non-zero exit codes in Win32Services
We have a python program cx-frozen into a Win32Service. The service must be running all the time and needs to recover from crashes automatically. 

In face of unhandled python exceptions (ie fatal error), the running service seems to exit with a zero exit code leading the service state to STOPPED state. This render any of the Windows Service Recovery strategies ineffective as they only respond to non-zero ExitCodes.

As a workaround, we have resorted to a secondary service that's always checking the state of the frozen service. If it's in STOPPED state, it restarts it. That's an extra layer of management we need to maintain.

Can the service api change in a way that the exit codes reflects more closely the outcome of python program's execution?

### PR DESCRIPTION
**Pull request by johan-ronnkvist**
# Intent: Resolve issue #898  

### How: 
Ensure that when the return value of `Service_Run()` is less than zero, we exit the service with an exit code of -1. This is done without setting the SERVICE_STOPPED state to indicate that this was not an intentional stop. 

According to the Windows API documentation, this is the expectation from the system.

> A service is considered failed when it terminates without reporting a status of SERVICE_STOPPED to the service controller.
[Source](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_failure_actionsa)

### Why: 
Enable services to communicate internal failures, so that an automatic restart policy can be applied.

### Testing:
Testing has been done in a pair-dev setup with @TechnicalPirate.

### CODE REVIEW

File: source/bases/Win32Service.c [hunk 1]
```diff
@@ -93,6 +93,14 @@ static int Service_SetStatus(udt_ServiceInfo* info, DWORD status)
...
         serviceStatus.dwControlsAccepted |= SERVICE_ACCEPT_SESSIONCHANGE;
+    if (exit_code == 0) {
+        serviceStatus.dwWin32ExitCode = 0;
+        serviceStatus.dwServiceSpecificExitCode = 0;
+    }
+    else {
+        serviceStatus.dwWin32ExitCode = ERROR_SERVICE_SPECIFIC_ERROR;
+        serviceStatus.dwServiceSpecificExitCode = exit_code;
+    }
     serviceStatus.dwWin32ExitCode = 0;
```
Comment (marcelotduarte) [inline source/bases/Win32Service.c]: The two lines overwrite the previous value.

Comment (johan-ronnkvist) [reply source/bases/Win32Service.c]: Thank you, fixed!

**Comment by marcelotduarte** [comment]
Compiler error:
```
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\runneradmin\AppData\Local\Temp\build-env-e99xypbk\include -IC:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.7.9\tools\include -IC:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.7.9\tools\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcsource/bases/Win32Service.c /Fobuild\temp.win32-cpython-37\Release\source/bases/Win32Service.obj
  Win32Service.c
  source/bases/Win32Service.c(87): error C2143: syntax error: missing ')' before '='
  source/bases/Win32Service.c(87): error C2072: 'Service_SetStatus': initialization of a function
  source/bases/Win32Service.c(87): error C2059: syntax error: ')'
  source/bases/Win32Service.c(88): error C2143: syntax error: missing ';' before '{'
  source/bases/Win32Service.c(88): error C2449: found '{' at file scope (missing function header?)
  source/bases/Win32Service.c(110): error C2059: syntax error: '}'
  source/bases/Win32Service.c(212): warning C4013: 'Service_Stop' undefined; assuming extern returning int
  source/bases/Win32Service.c(283): error C2198: 'Service_SetStatus': too few arguments for call
  source/bases/Win32Service.c(552): error C2198: 'Service_SetStatus': too few arguments for call
  source/bases/Win32Service.c(613): error C2198: 'Service_SetStatus': too few arguments for call
```

**Comment by marcelotduarte** [comment]
Thanks!
