### PR TITLE
when building from sources, get cx_Logging to build Win32Service.exe

### LINKED ISSUE #519: Win32Service.exe base doesn't get built
When you build 6.0 the Win32Service.exe base doesn't get built, it's just silently ignored. You need to have cx_Logging available - not installed but a built distribution in a parallel directory without the version number (i.e. "cx_Logging" not "cx_Logging-2.2")

Also, the cx_Logging 2.2 tar ball is missing the cx_Logging.h so it doesn't build. I had to pull that from GitHub and drop it into cx_Logging\src

Finally, the cx_Freeze build will still fail if cx_Logging.h isn't also put into the root of cx_Logging!

Since cx_Logging hasn't changed in years could it not be included in the cx_Freeze tar ball so you can build Win32Service.exe without so much pain!?

### PR DESCRIPTION
**Pull request by marcelotduarte**
fix #519 
If the source cannot be obtained, it silently fails, as it currently does.
Also:
- Win32Service - replace deprecated functions that will be removed in py4
- cleanup samples

### CODE REVIEW

File: source/bases/Win32Service.c [hunk 1]
```diff
@@ -494,10 +499,11 @@ static int Service_Uninstall(
         return LogWin32Error(GetLastError(), "cannot open service manager");
 
     // create service
-    serviceHandle = OpenServiceW(managerHandle, PyUnicode_AS_UNICODE(fullName),
-            SERVICE_ALL_ACCESS);
+    wfullName = PyUnicode_AsWideCharString(fullName, NULL);
+    serviceHandle = OpenServiceW(managerHandle, wfullName, SERVICE_ALL_ACCESS);
     if (!serviceHandle)
         return LogWin32Error(GetLastError(), "cannot open service");
+    PyMem_Free(wfullName);
```
Comment (anthony-tuininga) [inline source/bases/Win32Service.c]: This should happen before the check on the service handle; otherwise, a potential memory leak occurs!

File: setup.py [hunk 2]
```diff
@@ -88,13 +88,27 @@ def get_ext_filename(self, name):
 
 
 def find_cx_Logging():
-    dirName = os.path.dirname(os.getcwd())
+    import subprocess
```
Comment (anthony-tuininga) [inline setup.py:91]: I think I'd prefer this to be a warning that cx_Logging was not found. The documentation (and the warning itself) can include the commands required to set things up, but they shouldn't just be run automatically, I think.

File: source/bases/Win32Service.c (hunk 1 above)
Comment (marcelotduarte) [reply source/bases/Win32Service.c]: I'll take a look.

File: setup.py (hunk 2 above)
Comment (marcelotduarte) [reply setup.py:91]: Only when compiling via sources will this happen, not in installations in general. For example, even if I had instructions, warning, or documentation I would prefer it to be automated and I think whoever opened the issue too. When I went to test issue #536, I had a good job to find out how to use cx_Logging, if it were automatic, it would be so simple.

File: source/bases/Win32Service.c (hunk 1 above)
Comment (marcelotduarte) [reply source/bases/Win32Service.c]: This leak and others resolved.

File: setup.py (hunk 2 above)
Comment (anthony-tuininga) [reply setup.py:91]: Ok. I can live with it. ;-)
